### ISSUE TITLE
cy.request show more details

### ISSUE THREAD

**Issue by zhex900** [archfz/cypress-terminal-report#10]
Currently cy.request does not print any content of the request. It will be good to print the same details as cy.route

I tried to add this to Cypress.on('log:added', options => {

      if (options.name === 'request' && options.hookName && options.hookName === 'test') {
        options.message = options.renderProps.message;
      }

To get more information like status, response I need to wait for the promise in options to resolve. But I don't know how to do that.

If I console.log(options) the data is in consoleProps But console.log(options.consoleProps) does show the data. I guess the promise is not resolved. How do I fix this?

**Comment by archfz** [comment]
We could experiment using the Cypress.on('command:ended') instead or with the Cypress('log:added'). Preferably use only the first event.

**Comment by archfz** [comment]
Fixed and released in 1.1.0.
