### ISSUE TITLE
warning " > cypress-terminal-report@3.2.1" has unmet peer dependency "mocha@>=3.5.0".

### ISSUE THREAD

**Issue by guyguy333** [archfz/cypress-terminal-report#103]
Hello,

Installing this package, we're having this warning:

```
warning " > cypress-terminal-report@3.2.1" has unmet peer dependency "mocha@>=3.5.0".
```

I guess mocha shouldn't be required when installing cypress-terminal-report in another project ?

Thanks

**Comment by archfz** [comment]
It is used for types, indeed it shouldnt. Is this causing issues?

**Comment by guyguy333** [comment]
No, your package works perfectly :)
