### ISSUE TITLE
Missing example for options for the support install in the ReadMe

### ISSUE THREAD

**Issue by ChrisZie** [archfz/cypress-terminal-report#105]
# Current behavior
The user wants to change options in the support install but they can't find any examples in the ReadMe/Documentation showing how to do that. Instead, the user needs to google for an example or needs to trial and error through their code.

# Expected behavior
The options in the support install have an example showing how to implement these options for the support install.

# ToDo
Add an example (I can do that as I have been through the current behavior and found a solution)

**Comment by archfz** [comment]
Fix released in 3.2.2 ; with the caveat that typescript types have been a bit degraded in the `installLogsCollector.d.ts`, but this shouldn't be a big problem. Also I believe this fix was necessary for proper npm 7 support.
