### ISSUE TITLE
Can't get this plugin to work  in our project, maybe it's a typescript thing?

### ISSUE THREAD

**Issue by alexbjorlig** [archfz/cypress-terminal-report#110]
We are trying to improve our debugging experience with Cypress, by installing this plugin.

We are using typescript for our e2e tests - and we can't get any outputs at all. I suppose the installation could be the culprit? Instead of modifying `cypress/plugins/index.js` we should just modify `cypress/plugins/index.ts` correct?

Or should the code itself also be altered, i.e. `require('cypress-terminal-report/src/installLogsCollector')();`?

Thanks for the help :)

**Comment by archfz** [comment]
Typescript should not affect installation. Make sure you add the proper requires in both support and plugins file of cypress. Also note that logs by default only appear if a test fails.

If it still doesnt work please post more details: support and plugins file contents, cypress versions, presence any other cypress plugins, os and node version.

**Comment by alexbjorlig** [comment]
Thanks for taking a look.

Cypress is version 7.7.0, Mac OS Catalina.

**support/index.ts**

```typescript
const options = {
    printLogsToConsole: 'always',
};
require('cypress-terminal-report/src/installLogsCollector')(options);

// Import commands.js using ES2015 syntax:
import './commands';

// Add support for "real" events, to enable stuff like hover 🇩🇰
import 'cypress-real-events/support';

```


**plugins/index.ts**

```typescript
module.exports = (on) => {
    require('cypress-terminal-report/src/installLogsPrinter')(on, {
        printLogsToConsole: 'always',
    });
    // on('file:preprocessor', cypressTypeScriptPreprocessor);
    // Added this workaround, based on this: https://github.com/cypress-io/github-action/pull/97
    on(
        'before:browser:launch',
        (browser, launchOptions: { preferences: any; args: string[]; extensions: string[] }) => {
            const { args } = launchOptions;
            if (browser.name === 'chrome') {
                args.push('--window-size=1280,720');
                port = ensureRdpPort(args);
                return launchOptions;
            }
        }
    );
    on('task', {
        // A bunch of tasks for setting up our db
}; 
```

Spec

```typescript
it.only('Should report some output to console', () => {
      expect(true).to.equal(false);
  });
```


Could this be related to the fact that our project is running es6 modules, with `types: module` in the root pacakge.json?

**Comment by archfz** [comment]
Are there no errors? The first thing I notice is that printLogsToConsole option is added to the support install as well. And we dont have that there, only in the plugin install. Also we have validation of the options and it should throw an error if you provide nonexistent options.

**Comment by alexbjorlig** [comment]
No errors. I removed printLogsToConsole options from the support install. Would it make sense to add a console.log statement somewhere in the `node_modules/cypress-terminal-report/src` folder to make sure the require statement is working as expected?

**Comment by archfz** [comment]
It is kindof strange that no errors were thrown with the incorrect options.

Looking further into your examples, I also see that the test doesn't really contain any cypress commands. Please try to add the following instead in the test `cy.get('.not-exists')`. This plugin can only capture and log cypress commands.

Otherwise yes you could put a console log in `installLogsPrinter.js` at the beginning of the `installLogsPrinter()` function, to check whether import is working. But I suspect that works, since otherwise the run should break with an error.

**Comment by alexbjorlig** [comment]
So after adding `console.log('🔥'.repeat(100))` in `installLogsPrinter.js`, I see flames in the cypress terminal window.

I updated the spec to do

```
.get('[data-cy=i-dont-exist', { timeout: 300 })
.should('exist')
```

The spec fails, but I don't get any log output other than built-in cypress commands.
![Screen Shot 2021-07-12 at 09 51 26](https://user-images.githubusercontent.com/9967422/125250631-c59a7b80-e2f6-11eb-8e9a-6e80cd80861d.png)

**Comment by archfz** [comment]
You could try to move the log in the task in `installLogsPrinter.js:61` just after `[CONSTANTS.TASK_NAME]: function (data) {`
Also you should try running with `cypress run` and see if that way it displays or not. In general the logging is meant for when cypress is ran from terminal and not GUI, but afaik last time I checked it was logging in GUI mode as well.

**Comment by alexbjorlig** [comment]
I now ran with `npx cypress run  -b chrome --spec cypress/integration/svelte/tag.spec.ts`, and moved the console.log statement to line 61, after the `function (data) {`.

But I don't get any console.log output.. (and it does not matter if I run `open` or `run`).

**Comment by archfz** [comment]
This would mean that something is wrong in the support install. Basically the support install is what is calling the actual task on the plugin install when tests pass or fail. You could try putting a console log in `cypress-terminal-report/src/installLogsCollector.js` as well.

Other tests could be done: for example try execute the tests in `electron` browser, and also try to remove other cypress plugins one by one as there might be a conflict with one of them.

Otherwise I have tested this plugin with 7.7.0 cypress version and it's working.

**Comment by alexbjorlig** [comment]
Ok, I will attempt to isolate the issue. Did you test the repo with typescript - and if that is the case would you mind sharing the  repo?

**Comment by archfz** [comment]
Checkout https://github.com/archfz/cypress-terminal-report-demo it's now with typescript.

**Comment by alexbjorlig** [comment]
Ok I think I found the problem. In our `cypress.json` file we have the option `"supportFile": "cypress/support/commands.ts"` (I'm not sure why, looking into this to determine if we can live without this property). But when that property is configured, cypress-terminal-report does not work.

**Comment by archfz** [comment]
That is incorrect. The commands file just needs to be imported in the support file. They both nee to be loaded in the browser. If you dont use the support file on that config then you have the support file uselessly.

**Comment by alexbjorlig** [comment]
Incorrect? I mean if you add `"supportFile": "cypress/support/commands.ts"` to the cypress.json in the  demo-repo, then `cypress-terminal-report-demo` is not working

**Comment by archfz** [comment]
Ofc it doesnt work, cause then you are not loading the support.js anywhere, which is loading the plugin on the browser side. Please be clear on what files cypress loads, that being one in browser one on node side and ofc the spec files. Cypress doesnt load 2 files separately for the browser, like support and commands. Please notice that the default cypress project init imports the commands file in the support js.

**Comment by alexbjorlig** [comment]
Makes sense now @archfz  - thanks for the patience and an AWESOME library. Next step for me is to do something about the log outputs, since we use colored output like this: 

```
cons:log (K): %ccreateForm-_qur8btwli,
              color: white; background-color: #291617; padding: 2px 6px; border-radius: 2px; font-size: 10px,
              name emitted value: P
```

How would you accomplish this - Read.me or html file? Alternatively I could also just use emojies, because then different log instances could still be visually seperated and it would work "out of the box" in both `.txt` and `.json` files :)
