### ISSUE TITLE
Commands from skipped tests are not logged to terminal

### ISSUE THREAD

**Issue by mmayors** [archfz/cypress-terminal-report#111]
First of all amazing work! I've spent more time than I should trying to re-route everything to stdout. This package has been a godsend.

#### Issue description
If a test is programmatically skipped with Mocha's `this.skip()` any commands made before `skip()` are not logged to the terminal, including commands in a beforeEach(). Is this intentional?  

#### Steps to reproduce the issue

* cypress: 7.7.0
* cypress-terminal-report: 3.2.2
* cypress.json - experimentalInteractiveRunEvents: true
* installLogsCollector - enableExtendedCollector: true

1. Write a global beforeEach in `support/index.js`
2. Write a test that invokes a command (or series of commands), chains the last one, then invokes `this.skip()`.

#### What's the expected result?
All commands invoked in step 2, including the global beforeEach are logged to the terminal.

#### What's the actual result?
None of the commands invoked in step 2 are logged to the terminal.

#### Additional details / screenshot

Minimal Repro: [https://github.com/mmayors/cypress-terminal-report-skipped-test](https://github.com/mmayors/cypress-terminal-report-skipped-test)

I noticed that when a test is skipped the [`test` event handler](https://github.com/archfz/cypress-terminal-report/blob/master/src/collector/LogCollectExtendedControl.js#L101) attached to Mocha is invoked twice: Once when the test begins and again after `this.skip()`.  The 2nd time the test argument has an `err` property set:

```
{
  "message": "sync skip; aborting execution",
  "name": "CypressError",
  "isPending": true,
  ...
}
```

I don't know how all the command logs are pulled together but it appears commands captured before `this.skip()` are being discarded because [`startTest`](https://github.com/archfz/cypress-terminal-report/blob/master/src/collector/LogCollectorState.js#L130) is called twice for the same test.  Let me know if you need any additional info!

**Comment by archfz** [comment]
Added support in 3.3.0. But please note that the error part is cypress issue https://github.com/cypress-io/cypress/issues/14867
