### ISSUE TITLE
Cannot read property of size "null"

### ISSUE THREAD

**Issue by thaiching** [archfz/cypress-terminal-report#119]
Hi, 
   While running my Cypress test suites, one of the network requests test is failing with the following error. 

```
The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read property 'size' of null
```
Here is a screen shot of the Cypress test runner

<img width="1440" alt="Untitled" src="https://user-images.githubusercontent.com/7057586/130237484-87433d7d-42cf-4025-8719-87762833b85b.png">

Thanks.

**Comment by archfz** [comment]
Fix released in 3.3.2
