### ISSUE TITLE
Support also console.log

### ISSUE THREAD

**Issue by strowk** [archfz/cypress-terminal-report#12]
I am using webassembly and all stdout goes to console.log. I wonder if that could be redirected too

**Comment by zhex900** [comment]
You want to redirect all the console.log in the browser to the node terminal on the server side? 

Is this what you want?

https://github.com/flotwig/cypress-log-to-output

**Comment by archfz** [comment]
Yes. I think we could add an option to lof all console type logs other then warning and error. But by default should be off. There are sites that would log a lot of irrelevant things there.

**Comment by archfz** [comment]
Fixed and released in 1.1.0.
