### ISSUE TITLE
Request overrides are disabled

### ISSUE THREAD

**Issue by ossistyle** [archfz/cypress-terminal-report#127]
If requests override each other, then the newest matching request should be called.
Somehow this plugin disables this order.

The workaround is to disable/remove 'cy:request' in options.collectTypes

Example:
Add the following overwrite to the /support/commands.js

```
Cypress.Commands.overwrite('request', (originalFn, ...args) => {
   let options = {};

  if (typeof args[0] === 'object' && args[0] !== null) {
    options = args[0];
  } else if (args.length === 1) {
    [options.url] = args;
  } else if (args.length === 2) {
    [options.method, options.url] = args;
  } else if (args.length === 3) {
    [options.method, options.url, options.body] = args;
  }

  let headers = options.headers || {};
  headers['User-Agent'] = 'Cypress'; 

// ... changing/adding more custom headers
  
  options.headers = headers;

  return originalFn(options);
});
```

In the real request overwrite we added baseAuth credentials which are not used but the example with the user-agent also works as an example, I hope.

In the request header no "User-Agent" = "Cypress" is shown.

**Comment by archfz** [comment]
So we had a similar issue with `cy.intercept`, but for that it was the case that the originalFn return value was not returned. See https://github.com/archfz/cypress-terminal-report/issues/120

So in case of `cy.request` we are returning see https://github.com/archfz/cypress-terminal-report/blob/aaf080474116cbd3f87bce6b6af1b74f3e15d3fc/src/collector/LogCollectCypressRequest.js#L96 So I am not sure what is going, could use some debugging help here.

**Comment by ossistyle** [comment]
Hello,
you can close the issue. After I updated the Cypress version to 9.0.0 I can see the request in the terminal.
Maybe this is not the fix but it works now for me.

If I have again this issue, I will open another ticket.
