### ISSUE TITLE
any way to set compactLogs for console while not compacting for output to log file?

### ISSUE THREAD

**Issue by bvandercar-vt** [archfz/cypress-terminal-report#138]
I want to use the `compactLogs` option in the terminal to limit the output, but output **all** logs to a file. Is this possible? If not, it should be-- would be nice to set entirely different configs for terminal output vs. file output.

**Comment by archfz** [comment]
This would be a new feature. The codebase is not that complex, contribution is welcome 😁.

**Comment by bvandercar-vt** [comment]
I can definitely work on the feature, shouldn't be too complex

**Comment by archfz** [comment]
Good job, thank you for your effort. Released in 3.5.0
