### ISSUE TITLE
Missing snapshot image error after installing cypress-terminal-report

### ISSUE THREAD

**Issue by ritchieanesco** [archfz/cypress-terminal-report#145]
First off, great plugin! Has helped our project debug issues with request payload and authentication tokens!

After installing cypress-terminal-report, we've noticed that cypress-snapshot-plugin no longer opens the modal to display changes in snapshot. It looks to have an impact on snapshots feature in cypress, as I'm seeing "snapshot is missing" in the command log.

## Expected Behavior
When a change occurs in the layout, a "snapshot comparison" link is available in the command log. On click of "snapshot comparison" a modal appears displaying the area of the layout that has been changed.

## Actual Behavior
When a change occurs in the layout, a "snapshot comparison" link is available in the command log. On click of "snapshot comparison" nothing happens.

Would you please advise us on how we can address this issue?
## Screenshot

![Screen Shot 2022-05-19 at 9 26 51 am](https://user-images.githubusercontent.com/1123992/169171461-fcb26374-c68c-4533-a553-58e47b616402.png)

**Comment by archfz** [comment]
Hmm. I am not sure if it is related or not. But it might be. Either way this is an issue in cypress-snapshot-plugin. Quite the coincidence but I also use this plugin on one of my projects. Aaaaand actually I created a PR in that plugin to fix this:

https://github.com/meinaart/cypress-plugin-snapshots/pull/207

I can only recommend installing patch-package and adding the contents of that PR as a patch. The maintainers of that project don't care about it. 

You might be interested in this one as well. https://github.com/meinaart/cypress-plugin-snapshots/pull/209

**Comment by ritchieanesco** [comment]
Thanks for getting back to @archfz. Will take a look.
