### ISSUE TITLE
TypeScript based Config for Cypress 10+

### ISSUE THREAD

**Issue by henryruhs** [archfz/cypress-terminal-report#148]
I wonder if this is the correct way to implement this plugin to a TypeScript based project.

# support/e2e.ts

```
import 'cypress-terminal-report/src/installLogsCollector';
```

# cypress.config.ts

```
import { defineConfig } from 'cypress';
import installLogsPrinter from 'cypress-terminal-report/src/installLogsPrinter';

export default defineConfig(
{
	e2e:
	{
		setupNodeEvents(on : Cypress.PluginEvents)
		{
			installLogsPrinter(on);
		}
	}
});
```

It says that installLogsPrinter is not a fuction but observing the `d.ts`gives me that information.

```
declare function installLogsPrinter(on: Cypress.PluginEvents, options?: PluginOptions): void;
export default installLogsPrinter;
```

**Comment by archfz** [comment]
https://github.com/archfz/cypress-terminal-report-demo
Please see here.
The solution is to add `esModuleInterop: true` in tsconfig.
I will update the readme as well.
