### ISSUE TITLE
Enhancement: allow filtering of logs

### ISSUE THREAD

**Issue by jrnail23** [archfz/cypress-terminal-report#15]
it would be great to be able to pass in a predicate of some sort to the support installer to filter out unwanted entries.

**Comment by Flaxline** [comment]
Yes, I actually just want to have cy.log - Entries and it would be amazing to be able to filter for that.

**Comment by archfz** [comment]
Implemented and released in 1.2.0.

**Comment by jrnail23** [comment]
thanks @archfz!
