### ISSUE TITLE
Doesn't record console logs from custom cypress commands

### ISSUE THREAD

**Issue by Maxim-Mazurok** [archfz/cypress-terminal-report#157]
When console.log in my web app occurred during the execution of a custom `cy.bla()` command declared as `Cypress.Commands.add('bla', ...` it didn't record any console.logs.
Workaround: instead of using custom command, export a function, which is my preference anyway because VS Code can navigate to the declaration in that case.
Still, might want to fix or add docs.
I'm using `v3.5.2` with cypress `v8.2.0`

**Comment by archfz** [comment]
I am not sure what you mean. Please provide more information, maybe a reproducible example.

The console methods are wrapped at the load of the plugin, but only the ones inside the iframe. Custom command, or any cypress command should not block that.

**Comment by Maxim-Mazurok** [comment]
So let's say that I have this:
```js
Cypress.Commands.add('bla', () => {
  cy.contains("click me").click()
}
```
and I have app code such as this:
```html
<button onClick="() => console.log("something")">click me</button>
```

So why I call `cy.bla()` it logs "something" in the browser console, but it wasn't detected in this plugin when running headless.

Workaround was to do this:
```js
export const bla = () => {
  cy.contains("click me").click()
}

bla();
```

**Comment by Maxim-Mazurok** [comment]
I might be wrong tho, we have a pretty complex app with intermittent issues that I'm debugging, so maybe I was expecting to see console log when the app in fact didn't log..

**Comment by archfz** [comment]
Will try to reproduce based on that and will come back to you.

**Comment by archfz** [comment]
I've attempted to reproduce but I have failed (ctr 3.5.2, cypress 9.3). Can you try if this works for you?

command.js:
```js
Cypress.Commands.add('customClickCommand', () => {
  cy.contains("Submit").click()
});
```

spec.js
```js
describe('Repro', () => {
  it('Repro', () => {
    cy.visit('https://example.cypress.io/commands/actions');
    cy.window()
      .then(w => w.document.querySelector('[type="submit"]').onclick = () => w.console.log('Logged message'));
    cy.customClickCommand();
    cy.get('not-found', {timeout: 1});
  });
});
```

I get the following results in terminal for this:
```
      cy:command +  visit       commands/actions
      cy:command +  window
      cy:command +  contains    Submit
      cy:command +  click
        cons:log i  Logged message
      cy:command x  get not-found
```

Additional info you should provide: OS, browser used, options you are sending to this plugin install.

**Comment by archfz** [comment]
Never mind I see your problem I think. 

```html
<button onClick="() => console.log("something")">click me</button>
``

You have a callback in onclick. That callback is not executed, you need to put the code directly in there:

```html 
<button onClick="console.log("something")">click me</button>
```

**Comment by Maxim-Mazurok** [comment]
Nah, that was just a pseudo-code for demonstration, not an actual code.
Either way, if it doesn't repro - I guess it works, I'll report back if I see this again, thank you for looking into this!
