### ISSUE TITLE
Cypress Errors are sometimes blocked by the log collector

### ISSUE THREAD

**Issue by jcom000** [archfz/cypress-terminal-report#158]
If I mess up my syntax in a describe block, I expect to see a reference error. For example, if I rename `it` to `fit` I expect
![image](https://user-images.githubusercontent.com/98349137/181139909-1105a050-22c1-4bb7-a064-ad67d6641f97.png)

however, with log collector enabled, I get a different error that I can click for info in dev tools
![image](https://user-images.githubusercontent.com/98349137/181139982-a7f6b4db-dfd6-42bf-aaae-f45c7b92d6b6.png)

and if I set
```
const log_collector_options = {
  enableExtendedCollector: true,
};
```
then I get no errors in the cypress bar, but the error shows in dev tools.
![image](https://user-images.githubusercontent.com/98349137/181140113-38909301-a1b0-463e-95ec-f2753cb10794.png)
![image](https://user-images.githubusercontent.com/98349137/181140165-86cb06a7-6fa2-48ac-8754-1c5e6367e1de.png)

**Comment by archfz** [comment]
I think this is related to https://github.com/archfz/cypress-terminal-report/issues/152

Please state you cypress version and this plugin version. I believe an update should fix this.

**Comment by jcom000** [comment]
you're right. upgrading solving it!
![image](https://user-images.githubusercontent.com/98349137/181340096-d626fac8-a458-4b3c-9cfb-ad68e022aecd.png)

**Comment by jcom000** [comment]
I was on cypress 1.3.0 and terminal report 4.0.1. upgrading to latest, 1.3.1 and 4.1.1 works just fine

**Comment by archfz** [comment]
Well that is by far not the latest on both this plugin and cypress. Also the fix I mentioned was done in 4.x.x of this plugin. But if it works on 1.3.1 then all good.
