### ISSUE TITLE
Cannot see GraphQL request/responses in log

### ISSUE THREAD

**Issue by RadomirNowak** [archfz/cypress-terminal-report#159]
Hi there!
The app that I'm working on uses GraphQL as its main integration. I've enabled the options to print requests and headers for XHR, but still don't see any other info than basic logs. Below you may find my configuration and a screenshot of how much info the logs contain. Are there any other options that I have to enable to see more?
```
require('cypress-terminal-report/src/installLogsPrinter')(on, {
    printLogsToConsole: 'always',
    routeTrimLength: 50000,
});
```
```
require('cypress-terminal-report/src/installLogsCollector')({
  xhr: {
    printHeaderData: true,
    printRequestData: true,
  },
});
```
![image](https://user-images.githubusercontent.com/11005257/182391346-26637e58-be6e-422f-b689-4d31f5a2fe21.png)

**Comment by archfz** [comment]
That should be it. Not sure why it's not working as we have tests for this. What version of the plugin and what version of cypress are you using.

**Comment by RadomirNowak** [comment]
Thanks for such quick response!
Cypress version: `9.5.2`
cypress-terminal-report version: `3.5.2`

**Comment by archfz** [comment]
@RadomirNowak Forgot about this. But basically we are only printing such data for requests that are intercepted / routed. The reason for this is, by assumption, that there can be many requests which one might not care in scope of the test, and printing the request data for all of them could just increase the log sizes and make them harder to read.

Your options are:
1. intercept the graphql calls, if you are not mocking them just let them pass through
2. transform this into a feature request if really needed, we could add a special options for this

For now I am only considering adding a note somewhere in the README about this.

**Comment by archfz** [comment]
Due to inactivity I will close this. Feel free to open a feature request if really needed.
