### ISSUE TITLE
Support for printing objects

### ISSUE THREAD

**Issue by pbadenski** [archfz/cypress-terminal-report#16]
Currently, if object is logged to the console you see: `cons:info ⓘ  [object Object]`.

It would be great if it would display contents of the object instead. A few ideas:
 - in most cases `JSON.stringify` would be sufficient
 - allow to enabled on a flag to avoid spamming
 - allow to provide a custom formatter for objects

**Comment by archfz** [comment]
What do you mean by custom formatter? What would be the use case?

**Comment by pbadenski** [comment]
Oh I think I'm bike shedding a bit. The easiest way is to add `JSON.stringify`.. I'm thinking for people who log very large objects they might want to customise this. I personally don't have this use case, so I would be totally comfortable with simple `JSON.stringify`.

**Comment by archfz** [comment]
Implemented and released in 1.2.0.
