### ISSUE TITLE
CypressTerminalReportPrinter.PluginOptions.includeSuccessfulHookLogs type is not optional

### ISSUE THREAD

**Issue by spiltcoffee** [archfz/cypress-terminal-report#161]
https://github.com/archfz/cypress-terminal-report/blob/78dfd0f7a9801c3146731b7a82328e80d6802f18/src/installLogsPrinter.d.ts#L106

Considering it's marked with a `@default` JSDoc annotation, and all of the other fields on the `PluginOptions` object are optional, it seems like this field should also be optional.

**Comment by archfz** [comment]
Fix released in 4.1.2
