### ISSUE TITLE
Logging appears in console only after tests have finished

### ISSUE THREAD

**Issue by ishaan-mehta** [archfz/cypress-terminal-report#165]
Great plugin!

Is there a way to see the logs in console output as soon as the action/warning/error occurs, rather than it dumping it all out at once at the conclusion of the test run?

**Comment by archfz** [comment]
https://github.com/archfz/cypress-terminal-report#optionsenablecontinuouslogging

**Comment by Josh68** [comment]
@archfz, this works, thank you. But how risky is it to enable? In this case, I'm limiting output to `cy.log`s, only, and these are my only 2 configuration options. With Cypress' `testIsolation`, for tests that make most sense as one long context block (`it`), it's very helpful to have continuous logging to console when using `cypress run`, but I don't want to create potential issues, particularly in CI.

**Comment by archfz** [comment]
@Josh68 I am unsure of the impacts. I am not sure what is the usage on this option and whether there are issues with it. There is a only on test for this feature. Given that this is your best option I would say try it and report back with it's stability. If all is good maybe we should update readme to remove some of the risk warnings.

**Comment by Josh68** [comment]
@archfz, thanks. So far, this is working for me as expected, but hasn't gone through all of our CI pipeline at every level. If I can figure out how to limit the tests that even leverage your plugin, that may be a good bet. My purpose for including it is to log steps (as they're processed) in long test blocks, and we have only a couple of those. They used to depend on carrying state over from previous tests, and I'm trying to stick with `testIsolation` now, with our upgrade.
