### ISSUE TITLE
Default request log clutters output

### ISSUE THREAD

**Issue by vxsl** [archfz/cypress-terminal-report#166]
Hi, great plugin! I'm not sure if I'm missing something, but I can't find a way to remove the default (unindented) Cypress dev server log output:

![image](https://user-images.githubusercontent.com/53827672/204299361-3f02f6c9-623f-45fe-adeb-47ec262d9dd4.png)

I can't find any mention of this output online except for [this question](https://stackoverflow.com/questions/62758813/is-there-a-way-to-hide-all-the-http-request-logs-from-the-node-terminal-output) which was never solved.

I can see that the screenshot in this project's README does not include these lines, so I'm thinking it must be possible:

![image](https://user-images.githubusercontent.com/53827672/204300311-69d9bcb1-b8d8-4d6f-b918-49585b96a521.png)

**Comment by archfz** [comment]
Afaik you get those logs during the GUI of cypress. But when you run in headless you don't. This plugin was not meant to show you logs while in GUI, as you can already see everything and even more in the GUI already.

**Comment by vxsl** [comment]
Thanks for the quick response.

Re: the issue: nevermind, I wrongly assumed [this answer](https://stackoverflow.com/a/68622538/5827204) would not work. It does!

> Afaik you get those logs during the GUI of cypress. But when you run in headless you don't. This plugin was not meant to show you logs while in GUI, as you can already see everything and even more in the GUI already.

I see. I guess I have a non-standard use case for this plugin, which is to be able to more easily navigate and grep the logs as tests are running in the GUI.
