### ISSUE TITLE
Save output to file

### ISSUE THREAD

**Issue by bjowes** [archfz/cypress-terminal-report#17]
Seeing the cypress log in the terminal is great - but when integrating with a CI environment it would be helpful if the output could be (easily) saved to a file. The file could then be uploaded as an attachment to the test run.

**Comment by archfz** [comment]
Hi. There is an issue for the dashboard if you mean for that. Other than that usually you see the output on the CI logs where you ran the cypress run command. What CI are we talking about?

**Comment by bjowes** [comment]
Azure Devops.

**Comment by bjowes** [comment]
And yes, I can see the result in the logs. But the logs are not very usable. We compose a html report with screenshots, and it would be great to be able to attach these logs there too.

**Comment by archfz** [comment]
Ok now I understand the use case. There are other modules that actually write reports in files. But as I saw they were lacking some output like request or console logs.

Would you require these outputs to be in plain txt? Or some json with specific structure?

**Comment by bjowes** [comment]
As a starting point I think plain text (utf-8) would do nicely.

**Comment by bjowes** [comment]
But there should be a way to identify which test case the log relates to. Could be deduced form the filename (like the failure screenshots in cypress)

**Comment by albadam000** [comment]
That would be useful for us as well. We're pushing all the cypress logs to ReportPortal, so even if it is a callback method where we can access the log data easily or just the possibility to save the logs as a file, any of them would be great.

**Comment by csvan** [comment]
This would be extremely useful

**Comment by archfz** [comment]
Released in 1.3.0.

**Comment by bjowes** [comment]
Thanks for implementing this! Also really nice that you added json format, it might be handy.

Suggestion:
When the log files are written, print a line to the log stating this. Example from Mochawesome:
```
[mochawesome] Report JSON saved to c:\Source\Repos\mpa_medis\e2e\cypress\results\json\mochawesome_023.json
```

**Comment by archfz** [comment]
@bjowes Can you open a separate issue please. Also contributions are welcome, this would be super easy to implement :)
