### ISSUE TITLE
Wrong message in correct assert

### ISSUE THREAD

**Issue by xavigimenezsanchez** [archfz/cypress-terminal-report#173]
Every time I have a correct assert comparing two strings, for instance, 
cy.get(".card__header__text").should("have.text", name);

Cypress-terminal-report is showing a wrong message:
cy:command ✔  assert	expected **.card__header__text** to have text **db1**, but the text was **''**

It is happening with the last version 5.0.1 and with version 3.5.2

**Comment by archfz** [comment]
I've tried to reproduce this in the https://github.com/archfz/cypress-terminal-report-demo by running `npx cypress run --spec cypress/integration/examples/assertions.spec.ts` but I get correct output: `cy:command ✔  assert    expected **<td>** to have text **Column content**`. The demo is on latest version both cypress and the plugin.

Is the output correct in the cypress GUI? Could you provide more details, preferably a minimal reproduction.

**Comment by xavigimenezsanchez** [comment]
In cypress GUI is correct. 

Details about how it is working:
- cy.visit is call it in beforeEach statement 
- An example of the output comparing texts:
- cy:command +  assert    expected **<span.main-head__header-bar__left__logo--bold>** to have text **PSLink**
        cy:command +  assert    expected **<span.main-head__header-bar__left__logo--light>** to have text **e2e-test-xavi**, but the text was **''**
- The difference between the first one and the second that appears the message "but the text was **''**" is that the second one needs more milliseconds to load.

If a cy.wait is put after the cy.visit the problem disappears

**Comment by archfz** [comment]
Fixed in 5.0.2. If backport needed into 3.x.x, contribution is welcome (https://github.com/archfz/cypress-terminal-report/pull/174/files).
