### ISSUE TITLE
Option to always log response body for cy:fetch

### ISSUE THREAD

**Issue by jeremybeard** [archfz/cypress-terminal-report#176]
If I understand correctly, "cy:request" logs the response body in all cases, but "cy:fetch" only logs the response body if the fetch failed. It would be good to have the option to log the response body in all cases for "cy:fetch".

**Comment by archfz** [comment]
Well apparently this is not supported by cypress currently. I've opened and issue let's see when they will fix it.

**Comment by archfz** [comment]
New link https://github.com/cypress-io/cypress/issues/21421
