### ISSUE TITLE
Abbility to import logs into report

### ISSUE THREAD

**Issue by irapths** [archfz/cypress-terminal-report#180]
Hello

This plugin is very helpfull during debuging failed tests.
But when run on CI it is not very convinient to search into the expoted log files to locate the failed test.

I'd like be able to import the collected logs of failed tests into the Mochawesome report as "additiona context" on test:after:run.
I can underestant that the log files are not yet created at this state, but later.
So I'm thinking of a different kind of data exposure and use it on test:after:run.
But "auto-import" by the plugin - activated by a new flag - could be also OK, if not even better.

For example I can import the video with the following simple code
```javascript
// @mension: https://glebbahmutov.com/blog/the-awesome-battle/
Cypress.on('test:after:run', function (test, runnable) {
    if (Cypress.Mochawesome) {
        if (Cypress.config('video')) {
            // Add video on failed test
            const videoFile = `${Cypress.config('videosFolder')}/${Cypress.spec.name}.mp4`
            Cypress.Mochawesome.context.push({
                title: 'Spec file execution video',
                value: videoFile
            })
        }
    }
});
```

An idea of the code to be used to add the logs into report is:
```javascript
Cypress.on('test:after:run', function (test, runnable) {
    if (Cypress.Mochawesome) {
        if (Cypress.TerminalLogs) {  // TerminalLogs: Placeholder for cypress-terminal-report presence check
            // Add collected terminal log
            Cypress.Mochawesome.context.push({
                title: `Execution log`,
                value: Cypress._.join(testLogs, '\n')  // testLogs: Placeholder for collected logs of the just-ended test
            })
        }
    }
});
```

Thank you for your work on this plugin
.

**Comment by archfz** [comment]
I have quickly glanced into the mochawesome report. I suppose we are talking here about the html generated output. And you would like to include the logs generated from this plugin into that right?

I haven't used mochawesome, but I am open to it and contribution is welcome.

Wouldn't this also require formatting the logs for proper html display? Also besides all this have you also considered configuring the plugin to  export logs in files only for failed tests?

In any case it seems to me that this should be enabled by a new config on the support install, and might also need a little bit of refactoring on how we send logs to node plugin side, as we would also need to direct them into this context push too on the support js side ( changes to be made in log collector controllers) + necessary formatting.

**Comment by archfz** [comment]
I am thinking that maybe we can go with something simple. This would be simpler if the processing of the logs for output into files would have happened in the browser, but they happen on node side.

We could add a `Cypress.TerminalReport.on('logs', (logs) => {}` . Also we might be able to extract the txt formatting and reuse it in the browser by `Cypress.TerminaReport.formatLogs('txt', logs)`. So in the end you could do on your side:

```js
Cypress.TerminalReport.on('logs', (logs) => {
            Cypress.Mochawesome.context.push({
                title: `Execution log`,
                value: Cypress.TerminalReport.formatLogs('txt', logs)
            })
});
```

**Comment by irapths** [comment]
This really nice aproach, since inside `Cypress.TerminalReport.on('logs', (logs) => {})` the user is free to use the collected TC logs whatever way he wants and at the right time (after TC completed).

Only one possible problem I can see here (and maybe **is not valid** at all), if the `Cypress.TerminalReport.on('logs', (logs) => {})` will be triggered wille `Cypress.Mochawesome` instance exists or not.

To be honest, I like the txt format but I think the JSON gives more freedom on formating the output. Or even better expose both formats.

Since, unfortunately, I cannot help with the code, and I don't know how much this feature will be used by other users, I just write here my thoughts.

**Comment by danyg** [comment]
Hi we also looking forward to this feature!
It would be way better for us to it to work in this way.

```ts
afterEach(() => {
  const data = Cypress.TerminalReport.getLogsOfCurrentTest().join('\n']);
  cy.addTestContext(`---[ Logs ]-------------------------------------------------------------:\n${data}`);
});
```
Although the proposed way also works, we could collect the logs per test in some way or another.
Using `cypress-mochawesome-reporter` which adds the `cy.addTestContext` command

**Comment by archfz** [comment]
Added support in 5.1.1; see [readme](https://github.com/archfz/cypress-terminal-report#cypress-mochawesome-reporter)
