### ISSUE TITLE
Not able to get console.log in the terminal

### ISSUE THREAD

**Issue by sahana-u** [archfz/cypress-terminal-report#187]
I'm not able to get console.log, console.info logs in the terminal. I'm only getting cy:command logs for every action in my test code. How can I get the console.log or console.info logs as well in the terminal? 
I have done the pre configs like adding installLogsPrinter in config file and adding installLogsCollector in e2e.ts. 
I just get the logs in terminal like this -
      cy:command ✔  session	automation@gmail.com
      cy:command ✔  Clear page	
      cy:command ✔  sessions_manager	
      cy:command ✔  session	
      cy:command ✔  visit	(url related log)
      cy:command ✔  url	
      cy:command ✔  assert	(assertion related log)

The console.log and console.info logs in the test are getting skipped.

**Comment by archfz** [comment]
Please read the README https://github.com/archfz/cypress-terminal-report#limitations-and-notes if you are talking about console logs from your test code. If you are talking about console logs from your tested application, then you might have another plugin that conflicts with this.

**Comment by sahana-u** [comment]
How do we use cons:info, cons:warn to provide specific info or warn logs? Should we just use cy.log instead? @archfz
