### ISSUE TITLE
How to use cons:info and cons:error in test to get info and error logs in terminal

### ISSUE THREAD

**Issue by sahana-u** [archfz/cypress-terminal-report#188]
How can we make use of cons:info and cons:error in our tests to get info and error logs in the terminal?
I get an error that says info is undefined on using cons.info()

**Comment by archfz** [comment]
console.info() is the way to call it. And if you read the readme properly you would understand that you cannot call this in test code. In test code use cy.log(). You can however call console methods in your website JS application code and those will appear in this plugins logs to terminal.
