### ISSUE TITLE
Cypress terminal report does not generate logs in CLI in Cypress 12.12.0.

### ISSUE THREAD

**Issue by Rodyb** [archfz/cypress-terminal-report#198]
Hi there, 

I would love to make use of this tool, it looks awesome but I am stuck on the installation. 
I have followed the npm read me, an article on medium and some other articles on Google but I can't get this to work. 

Browser: electron

I did
```
npm i --save-dev cypress-terminal-report
```
And I added this to the config
cypress.config.js
```  },
  e2e: {
    setupNodeEvents(cypressOn, config) {
      const on = require('cypress-on-fix')(cypressOn)
      require('./cypress/plugins/index.js')(on, config)
      require('cypress-split')(on, config)
      require('cypress-terminal-report/src/installLogsPrinter')(on);
    },
  ```

cypress/support/e2e.{js|ts}

```
import "./commands";
const options_log_collector = {
  printLogsToConsole: "always",
  collectTypes: ["cy:log", "cy:command"]
};
require('cypress-terminal-report/src/installLogsCollector')(options_log_collector);
```

test.js
```
  it("Verify logging", () => {
    cy.visit('/customer')
    cy.log('test logging ')
  });
});

```
OUTPUT
<img width="583" alt="Screenshot 2023-07-10 at 18 50 11" src="https://github.com/archfz/cypress-terminal-report/assets/11462303/f79aab5f-e188-46d4-9c58-75123a469bdc">

What am I missing here? I am not getting an error and following the steps as described nor am I seeing any output in the logs.I also used the standard node events and the logging to a file both did not work. 

Hope you can help me, 

Thanks!

**Comment by archfz** [comment]
Do you have any cy.log in your test code? What version of CTR are you using?

**Comment by archfz** [comment]
Print logs to console is a plugin install option, not a support install option. https://github.com/archfz/cypress-terminal-report#optionsprintlogstoconsole
