### ISSUE TITLE
I see no extra output during `cypress run` when using plugin

### ISSUE THREAD

**Issue by jennifer-shehane** [archfz/cypress-terminal-report#2]
I followed the instructions in the README.md and don't see any extra output during `cypress run` in my local terminal (which I'm assuming is where the output is supposed to be although this wasn't specified).

`package.json`

```json
{
  "name": "cypress-test",
  "scripts": {
    "cypress:run": "cypress run --project cypress"
  },
  "dependencies": {},
  "devDependencies": {
    "cypress": "4.0.0",
    "cypress-terminal-report": "^0.2.2"
  }
}
```

`plugins/index.js`

```js
module.exports = (on) => {
  require('cypress-terminal-report').installPlugin(on);
};
```

`support/index.js`

```js
require('cypress-terminal-report').installSupport();
```

`cypress.json` - no special config that would overwrite these files

```json
{}
```

`spec.js` My spec has a bunch of commands!

```js
it('.type() - type into a DOM element', () => {
  cy.visit('http://example.cypress.io/commands/actions')
  cy.get('.action-email')
    .type('fake@email.com').should('have.value', 'fake@email.com')
    .type('{leftarrow}{rightarrow}{uparrow}{downarrow}')
    .type('{del}{selectall}{backspace}')
    .type('{alt}{option}') //these are equivalent
    .type('{ctrl}{control}') //these are equivalent
    .type('{meta}{command}{cmd}') //these are equivalent
    .type('{shift}')
    .type('slow.typing@email.com', { delay: 100 })
    .should('have.value', 'slow.typing@email.com')

  cy.get('.action-disabled')
    .type('disabled error checking', { force: true })
    .should('have.value', 'disabled error checking')
})
```

Output of `cypress run`

<img width="829" alt="Screen Shot 2020-02-12 at 11 39 07 AM" src="https://user-images.githubusercontent.com/1271364/74304945-df93ff80-4d8c-11ea-891b-ca4fe7e5abee.png">

**Comment by archfz** [comment]
@jennifer-shehane Your test is passing and that's why you don't see logs. There is not reason to write out detailed steps of a test that is not failing. Or at least I do not see need for it so currently that is not supported. Just make the test failing at some point to see the logs. Maybe write a random get at the end. 

Anyways if support for logging event for successful tests is requested by community then I will add it.

**Comment by jennifer-shehane** [comment]
@archfz This is not clear at all from the README. Can you add this information to the readme - that it only logs during failed tests? Because this is not explained anywhere.

**Comment by archfz** [comment]
Its literally in the first sentence: Plugin for cypress that adds better terminal output *when tests fail* on the terminal for better debugging. 

Maybe you can help me better formulate it?

**Comment by archfz** [comment]
I've highlighted that part in the text. Please check the MR if it's ok.

**Comment by jennifer-shehane** [comment]
Ok, yah, I don't know, I did read the Readme and missed this 🤷‍♀
