### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by robinst** [archfz/cypress-terminal-report#20]
I have a test that is conditionally skipped like this:

```
describe('My test', function() {
  before(function() {
    // Skip the tests on some environments as the feature is not enabled yet.
    if (Cypress.env('MY_URL')) {
      cy.login();
    } else {
      this.skip();
    }
  });

  it('tests the thing', function() {
    ...
  });
});
```

This works when I don't have cypress-terminal-report. But when I add cypress-terminal-report, in for the skip case, it fails like this:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'Jira issues in PR sidebar test'
    at $Cypress.<anonymous> (installLogsCollector.js:40)
```

The line from the stack trace: https://github.com/archfz/cypress-terminal-report/blob/master/src/installLogsCollector.js#L40

I think it's because in this case, `logs` is empty.

**Comment by archfz** [comment]
This should be quite easy to fix. We need to add a simple test case just like your example with the skipping test in test.js and after that apply the fix. Would you like to contribute?

**Comment by robinst** [comment]
Done, #21.

**Comment by robinst** [comment]
Looks like 1.2.1 fixed the problem
