### ISSUE TITLE
Options for specifying request-modifying callback

### ISSUE THREAD

**Issue by omega** [archfz/cypress-terminal-report#200]
I love this "plugin" for cypress, but we can't enable the request-logging, because we have to overwrite the `request` command to specify basic auth, and that then gets overwritten by `terminal-report`. So I was wondering if there would be interest in either an option to specify a callback to modify request and/or headers that `terminal-report` then calls before passing the request on to cypress, or if there could be added specific support for basic auth as config to `terminal-report`.

I could give a pull request a go, but wanted to check if there was any chance of getting it merged before I give it a go :)

**Comment by archfz** [comment]
We are using `Cypress.Commands.overwrite('request', ...` if you check in https://github.com/archfz/cypress-terminal-report/blob/master/src/collector/LogCollectCypressRequest.js 

From my understanding this will overwrite the previous version of the handler, so basically if you first do your overwrite and then call the plugin install, then it should use your previous handler in `originalFn`. https://docs.cypress.io/api/cypress-api/custom-commands#Overwrite-Existing-Commands

Maybe I am missing something, or this is not working this way and `originalFn` is always cypress handler.

**Comment by omega** [comment]
Not sure how best to verify this, but here is what I've tried.

I added logging to both my own overwrite, and the terminal-report overwrite, to see what happens when. The first line is from my `commands.ts`, and the second from `LogCollectCypressRequest.js`

```
in commands, should overwrite request
About to overwrite from terminal-report
```

So both calls to `overwrite` happens, mine first, then terminal-report.

I also added logging inside both the "overwritten" functions, my own and terminal-report.

When I then make a `cy.request` only the logging from terminal-report happens.

If I turn off `cy:request` log collection, I only get my own overwrite setup, and I get the logging from inside my own overwrite.

So it seems to only ever overwrite the cypress implementation of `request`, it doesn't seem to allow chaining 😢

**Comment by omega** [comment]
Found a reference to something related in a github issue for cypress, where it is stated that "the last overwrite will overwrite all other"
https://github.com/cypress-io/cypress/issues/9557

**Comment by archfz** [comment]
Ok, not very intuitive. In this case the solution to have some kindof option callback to this plugin is acceptable, maybe try to make it in way that it can be used for other purposes as well besides auth.

**Comment by omega** [comment]
sorry for going silent here! We decided to change our auth instead, to avoid this problem, so I'll close this issue, as I won't be prioritizing it anymore.

Sorry again for the noise I generated, and thank you for an amazing plugin
