### ISSUE TITLE
Is there a way to get the logging to write/append to the file in the afterEach portion of test runs.

### ISSUE THREAD

**Issue by eugenebu** [archfz/cypress-terminal-report#201]
I am working on a custom logging script that sends logs to our elastic search with details from tests.  I would like to send the terminal console logs of the failed tests in the suite in the after sections.  Currently I have a work around where after all the tests in our pipeline have run I scan for logs and send them.  I would like to make the tests logging self contained so I would not need an after after script. Is this possible?

**Comment by archfz** [comment]
I think you are looking for the [collectTestLogs](https://docs.cypress.io/api/cypress-api/custom-commands#Overwrite-Existing-Commands) callback config on the plugin install side. You can filter here for failed tests and send directly to elastic.

**Comment by eugenebu** [comment]
I found out that I could get the log data in the afterEach with this 
  cy.wait(50).then(() => {
  const logs = Cypress.TerminalReport.getLogs('json');
  cy.sendLogsApiCustomCommand(logs)
   })

**Comment by archfz** [comment]
Closing as solution exists.
