### ISSUE TITLE
Commands from subsequent test retries are not logged to console

### ISSUE THREAD

**Issue by mmayors** [archfz/cypress-terminal-report#214]
Hey peoples.

When [a test is retried](https://docs.cypress.io/guides/guides/test-retries#Configure-Test-Retries) and `printLogsToConsole` is set to `always`, only commands from the first attempt are printed to the console.  For example, given this test with retries set to `2`:
```
it('Test', () => {
    const currentRetry = cy.state('runnable')._currentRetry;

    cy.log('Hello. currentRetry:', currentRetry);
 
    if (currentRetry < 2) {
        cy.contains('Foobar', { timeout: 0 });
    }

    cy.log('Done.');
});
```

**Actual terminal output:**

```
  (Attempt 1 of 3) Test
          cy:log ✱  Hello. currentRetry: 0
      cy:command ✘  contains	Foobar


  (Attempt 2 of 3) Test
  ✓ Test (28ms)

  1 passing (535ms)
```

**Expected terminal output:**
```
  (Attempt 1 of 3) Test
          cy:log ✱  Hello. currentRetry: 0
      cy:command ✘  contains	Foobar


  (Attempt 2 of 3) Test
          cy:log ✱  Hello. currentRetry: 1
      cy:command ✘  contains	Foobar


  (Attempt 3 of 3) Test
          cy:log ✱  Hello. currentRetry: 2
          cy:log ✱  Done.
```

**Environment:**
- cypress-terminal-report: 5.3.6
- cypress: 12.17.4
- browser: electron

**Some rudimentary debugging:**
Seems the [check for `invocationDetails`](https://github.com/archfz/cypress-terminal-report/blob/master/src/collector/LogCollectSimpleControl.js#L23) is causing `sendLogsToPrinter` to return early. `invocationDetails` is present for the first attempt but not for subsequent attempts.  On subsequent attempts, the mochaRunnable (Test) has a `prevAttempts` property which is an Array of Tests:

<img width="595" alt="mochaRunnable-prevAttempts" src="https://github.com/archfz/cypress-terminal-report/assets/18597513/7d47e904-9623-4a57-9e72-076be49f890d">

Let me know if you need any additional info. Here's a repro: [test-retry-repro.zip](https://github.com/archfz/cypress-terminal-report/files/12729394/test-retry-repro.zip)

**Comment by archfz** [comment]
Release in 5.3.7
