### ISSUE TITLE
Integration with cypress-io/github-action@v6

### ISSUE THREAD

**Issue by aelgn** [archfz/cypress-terminal-report#215]
I've got awesome utility from this project when running `cypress run` locally. For some reason there is no console output when running with the cypress-io/github-action@v6.

I'm using the config `{ printLogsToConsole: 'always' }`

Any pointers?

**Comment by archfz** [comment]
I will need some more info. Paste in what is the output of the job. Is it the same project that works locally but not in github actions? Easiest would be if you can provide a minimal reproducible example.

**Comment by aelgn** [comment]
There was an error in the way we used promises to asynchronously seed the test environment. Once that was sorted, the command log was printed to stdout as expected.
Sorry to have wasted your time, and thank you for a great plugin 👍
