### ISSUE TITLE
Vulnerability - semver - Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by kis** [archfz/cypress-terminal-report#218]
Please update semver to latest version

**Introduced through**
cypress-terminal-report@5.3.3, @mocks-server/main@4.1.0 and others
**Fixed in**
semver@5.7.2, @6.3.1, @7.5.2

**Introduced through**: sastrify-e2e-tests@1.0.0 › cypress-terminal-report@5.3.3 › semver@7.3.8

**Comment by kis** [comment]
@archfz Please update semver to latest version to avoid vulnerability

**Comment by archfz** [comment]
Release in 5.3.8
