### ISSUE TITLE
Doesn't work with Component tests

### ISSUE THREAD

**Issue by piotrpalek** [archfz/cypress-terminal-report#220]
Hey! I've tried to use this plugin with component tests, but it seems that Cypress [doesn't fire](https://github.com/cypress-io/cypress/issues/17707) the `window:before:load` event in this type of test, so registering the plugin doesn't work correctly. 
Any chance we can fix this for component tests?

**Comment by archfz** [comment]
I guess you mean console logs are not working, as that is the only place we use that event. Other logs should work. Do you see an alternative?

**Comment by piotrpalek** [comment]
> I guess you mean console logs are not working
Yes, exactly :) They mention that `test:before:run` can be used instead

**Comment by archfz** [comment]
Release in 5.3.8
