### ISSUE TITLE
unconditional "debugger" statement is pausing execution for all tests that use LogCollectCypressFetch

### ISSUE THREAD

**Issue by mhseiden** [archfz/cypress-terminal-report#221]
A recent PR added a call to `debugger` into `LogCollectCypressFetch`. I'd imagine this was not an intended addition. However, if it was, placing it behind a config flag would be much appreciated. As is this change makes it impossible to run tests w/ the debugger open.

https://github.com/archfz/cypress-terminal-report/commit/c8cecd9b273d4a39dd5514c45b23b41f94b1150a#diff-90c9af081460757175536d7f5a49daa84f3f7d79a9fe50527717e173817fa678R56

**Comment by archfz** [comment]
Indeed. Removed in 5.3.9
