### ISSUE TITLE
How to filter `Verbose level`

### ISSUE THREAD

**Issue by hadothanh** [archfz/cypress-terminal-report#222]
Currently I saw list of log level are supported:
```
https://github.com/archfz/cypress-terminal-report#optionscollecttypes
array; default: ['cons:log','cons:info', 'cons:warn', 'cons:error', 'cy:log', 'cy:xhr', 'cy:request', 'cy:intercept', 'cy:command'] What types of logs to collect and print. By default all types are enabled. The 'cy:command' is the general type that contain all types of commands that are not specially treated.

```
how i access `cons:verbose`
![Screenshot 2023-11-06 at 20 05 42](https://github.com/archfz/cypress-terminal-report/assets/102339278/36589065-0b77-4242-8daf-d86ceab3327e)

**Comment by archfz** [comment]
To which method are you refering to https://developer.mozilla.org/en-US/docs/Web/API/console Only info, log, warn and error are captured at the moment by this plugin.

**Comment by hadothanh** [comment]
thank you @archfz for reply
