### ISSUE TITLE
Integration with cypress-mochawesome-reporter

### ISSUE THREAD

**Issue by vaclavGabriel** [archfz/cypress-terminal-report#233]
Hello, 
May I ask for clarification on the integration with `cypress-mochawesome-reporter`? 

According to the [documentation](https://github.com/archfz/cypress-terminal-report?tab=readme-ov-file#cypress-mochawesome-reporter), I've set up the integration in the `e2e.ts` file: 
```
import 'cypress-terminal-report/src/installLogsCollector'

afterEach(() => {
	cy.wait(50, { log: false }).then(() =>
		cy.addTestContext(Cypress.TerminalReport.getLogs('txt'))
	)
})
```

However, I'm getting this TS error: `Property 'TerminalReport' does not exist on type 'Cypress & CyEventEmitter'` 
Can you advise how to fix it, please? 

`package.json`:
```
"cypress-terminal-report": "^5.3.11",
"cypress-mochawesome-reporter": "^3.8.0",
"cypress": "12.17.3",
```

`tsconfig.json`:
```
	"compilerOptions": {
		"types": [
			"node",
			"cypress",
			"@testing-library/cypress",
			"cypress-terminal-report",
			"cypress-mochawesome-reporter"
		],
		"esModuleInterop": true,
```

**Comment by archfz** [comment]
Fix released in 5.3.12

Also added example integration in [demo](https://github.com/archfz/cypress-terminal-report-demo).

cc @bvandercar-vt Not sure why the change I made fixes it and why it was not working with your change.
