### ISSUE TITLE
Console errors are not retrieved during Hooks v6.0.0

### ISSUE THREAD

**Issue by mylmor** [archfz/cypress-terminal-report#235]
Hello, I'm trying to get console errors from hooks. (using v6.0.0)
I'm currently collecting with :
````
require('cypress-terminal-report/src/installLogsCollector')({
  commandTimings: 'timestamp',
  enableExtendedCollector: true,
});
```` 
and displaying it  with : 
````
'cypress-terminal-report': {
      outputRoot: `${config.projectRoot}`,
      outputTarget: {
        'logs|txt': 'txt',
      },
      includeSuccessfulHookLogs: true,
      printLogsToConsole: 'always',
    },
```` 
   I'm getting everything except the console logs during hooks.
   It seems to work fine during test execution though.

**Comment by archfz** [comment]
First please read https://github.com/archfz/cypress-terminal-report?tab=readme-ov-file#limitations-and-notes

Then if you case is different than post a reproducible example.

**Comment by mylmor** [comment]
I see so console errors coming from Cypress tests won't be logged.
Thanks for the response !
