### ISSUE TITLE
enableExtendedCollector prevents usage of Cypress on fail event

### ISSUE THREAD

**Issue by mylmor** [archfz/cypress-terminal-report#238]
Using enableExtendedCollector in the installLogsCollector seems to prevent me from using Cypress.on('fail', (error, runnable));
I'm able to see the "LOOK AT ME" just fine if I don't enable the enableExtendedCollector in the config.

in e2e.ts
```
Cypress.on('fail', (error, runnable) => {
  console.log('LOOK AT ME');
  throw error; // throw error to have test still fail
});

require('cypress-terminal-report/src/installLogsCollector')({
  commandTimings: 'timestamp',
  enableExtendedCollector: true,
});
````

**Comment by archfz** [comment]
The plugin has the following logic: https://github.com/archfz/cypress-terminal-report/blob/ad34c8751c10cb992a70c8eeeb9f84729133cb51/src/collector/LogCollectExtendedControl.js#L200

Maybe try to do `prependListener` after you registered the plugin.

**Comment by mylmor** [comment]
Seems to work without breaking the lib.
Thanks !
