### ISSUE TITLE
Is it possible to turn off the after each hook log?

### ISSUE THREAD

**Issue by triori** [archfz/cypress-terminal-report#239]
https://github.com/triori/badeball_cypress-if

This is a small repo with three of useless test.
The modules and structure used are the same as in my work project.
You can run it like npx cypress run and at the end of failed test log you can see

```
cy:command ✔  task        cypress-cucumber-preprocessor:test-step-finished, Object{4}
cy:command ✔  task        cypress-cucumber-preprocessor:test-case-finished, Object{3}
```

<img width="1300" alt="314367661-c0cc9215-ba98-4615-a4ac-6d77877ffa9f" src="https://github.com/archfz/cypress-terminal-report/assets/33620036/56c89f3f-7323-4d30-a239-c8f47cdca3a7">

I don't use any afterEach hooks or something like that. Can I turn off this logs?

**Comment by archfz** [comment]
Those are not afterEach hook logs. Those seem standard logs from the cucumber preprocessor. I would presume the same logs also appear in the cypress UI. Please consult the documentation on https://github.com/badeball/cypress-cucumber-preprocessor?tab=readme-ov-file if there is any way to turn that log off. If not you will have to open an issue on their side.

**Comment by triori** [comment]
I opened the same issue in Bahmutov cypress-if repo, maybe it will be useful for community. https://github.com/bahmutov/cypress-if/issues/69
Just in case ;)
