### ISSUE TITLE
printLogsToConsole: 'never' not respected by enableExtendedCollector: true when includeSuccessfulHookLogs is also true

### ISSUE THREAD

**Issue by gbutt-tr** [archfz/cypress-terminal-report#241]
When printLogsToConsole is set to 'never', enableExtendedCollector is set to true, and includeSuccessfulHookLogs is set to true, then before-all logs are still printed to the console.

Disabling includeSuccessfulHookLogs seems to fix this without any loss of file log data.

It is possible that these logs get output due to a hostname change that happens in the before hook, which causes the cypress spec to restart.

"cypress-terminal-report": "^6.0.1"
"cypress": "^13.6.4"

**Comment by archfz** [comment]
Fixed in 6.0.2

**Comment by phil294** [comment]
Seems to still be broken with `printLogsToConsole: 'onFail'`. The `beforeAll` logs are always printed. Setting `includeSuccessfulHookLogs: false` fixes this. (7.3.3)

Thanks for all your work on this plugin so far Fodor. Cypress is borderline unusable without it.
