### ISSUE TITLE
logging to file doesn't include logs from all attempts

### ISSUE THREAD

**Issue by parkuman** [archfz/cypress-terminal-report#242]
Hi there! Love the project and just started investigating using it on our CI. I noticed that when logging to a file, it doesn't log every attempt. I think this information could be very useful if a test is retried multiple times and fails for different reasons.

**Comment by archfz** [comment]
This kindof was broken due to some change in cypress. See https://github.com/cypress-io/cypress/issues/8413

But I checked the UI and their change makes sense. So I have just quickly re-implemented this for the plugins purpose.

Released in 6.1.0

**Comment by parkuman** [comment]
Thank you! Very much appreciated
