### ISSUE TITLE
Missing xhr.printBody in installLogsCollector.schema.json

### ISSUE THREAD

**Issue by khoelldobler** [archfz/cypress-terminal-report#248]
The `installLogsCollector.schema.json` is missing the option `xhr.printBody`. While available in the documentation and also within the implementation` installLogsCollector.js`, the schema does not include the option which leads to the following error:

  > cypress-terminal-report: Invalid plugin install options:
=> .xhr/printBody: Additional properties not allowed

**Comment by archfz** [comment]
Fixed in 6.1.1
