### ISSUE TITLE
Support to output the last few logs.

### ISSUE THREAD

**Issue by JFRabbit** [archfz/cypress-terminal-report#27]
In general, only output last few logs can confirm fail reason, instead of output all logs when failed.
Some case steps are very huge, too much logs are not friendly, should use some option to limit quantity.

For example, user can set option to only output last 10 command or other type logs when case failed.

**Comment by archfz** [comment]
It should be noted that sometimes the failing command is not even in the last 10 executed commands.

**Comment by archfz** [comment]
Also there are cases where other commands higher up the chain cause or point to the reason of failure below. Like for example console.error.

Maybe what we could do is like display only failing commands and max N amount of logs around these failing commands, if this option is enabled.

**Comment by archfz** [comment]
Released in 1.4.0
