### ISSUE TITLE
Print the full path to files when logging to file

### ISSUE THREAD

**Issue by bjowes** [archfz/cypress-terminal-report#29]
For clarify, add the full path of each file created by the plugin to the console logs.

**Comment by bjowes** [comment]
I'll be happy to implement this and submit a PR

**Comment by archfz** [comment]
@bjowes That would be nice. The development on this project should be simple. The test directory contains a full setup that emulates a cypress project using this cypress plugin. You can easily manually test your changes with it. Test case where you can include the expectation for this feature already exists. Don't forget to read the development section in the readme. If you have any questions feel free to ask.

**Comment by bjowes** [comment]
Development itself was fairly simple, but the unit tests revealed that some refactoring was required for proper support of win32 platform. Might be interesting to add a win32 step to the CI too.

**Comment by archfz** [comment]
Released in 1.4.1.
