### ISSUE TITLE
Potentially wrongly labeled failing command

### ISSUE THREAD

**Issue by archfz** [archfz/cypress-terminal-report#3]
Due to the async nature of the cypress testing flow commands can get executed after the actual failing command. We are presuming that the last registered command is the failing one so in these cases the wrong command will be labeled as the incorrect one. We should see if there is a better way to detect which commands failed.

This issue can potentially confuse people.

**Comment by zhex900** [comment]
I noticed this as well, the last command is logged as failed.

**Comment by zhex900** [comment]
How are about using `options.state` to check if the command or assert failed or passed

```
  Cypress.on('log:added', options => {
    if (options.instrument === 'command' && options.consoleProps) {
      if (options.name === 'log' || (options.name === 'task' && options.message.match(/terminalLogs/))) {
        return;
      }
      let detailMessage = '';
      if (options.name === 'xhr') {
        detailMessage = (options.consoleProps.Stubbed === 'Yes' ? 'STUBBED ' : '') + options.consoleProps.Method + ' ' + options.consoleProps.URL;
      }
      const log = JSON.stringify(options)+options.name + '\t' + options.message + (detailMessage !== '' ? ' ' + detailMessage : '');
      // options have a property state. 
      logs.push(['cy:command', log])
    }
  });
