### ISSUE TITLE
Log of assertion doesn't contain full expected value

### ISSUE THREAD

**Issue by PritamSangani** [archfz/cypress-terminal-report#46]
Hi. 

I have a cypress assertion: `cy.title().should('equal', 'Hello - World')` (This is just an example with the same format as the assertion that I am trying to do). If this assertion fails (e.g. the text should be `Hello - World!`, the log that I am getting is: `assert      expected **Hello** to equal **Hello - World!**`

Is this a bug, or is there some config I haven't enabled?

**Comment by archfz** [comment]
I do not understand which part is missing. The cy title command should also be logged by default. Comparing GUI and the terminal logs which part is missing?

**Comment by PritamSangani** [comment]
The cy title command does get logged out but the expected assertion string is cut off like in the example I showed you above. In the GUI it shows correctly, it just gets stripped in the terminal log.
