### ISSUE TITLE
Add option to write logs only to file avoiding print to terminal

### ISSUE THREAD

**Issue by sergeyKhristenko** [archfz/cypress-terminal-report#47]
I would like to have all the logs (not just `onFail`) in a file, having all of them printed to terminal looks too spammy. But it seems like print to terminal currently is inevitable. Is it possible to add some config option to print to file only?

**Comment by archfz** [comment]
We should duplicate the option for when to write logs for file outputs. Also add additional option for those 'never'

**Comment by zvaehn** [comment]
note that there are two different collectors.
One is called printer, the other one is the collector. (installLogsPrinter and installLogsCollector)
You can set the printer to "onFail" and the Collector to "always".

**Comment by archfz** [comment]
@zvaehn What you are saying was not possible in previous versions either. Now we have proper validation on config to prevent you from sending unused config.

Also we dont have two collectors. There is only one collector which is in the support install, that collects the logs and later on sends it to the nod js (the plugin install / the printer) where they actually are written to console and file.

**Comment by zvaehn** [comment]
Well, this sounds much more plausible. Thanks for pointing that out.
I am also interested in differenciating between console output and file-logging output.

**Comment by archfz** [comment]
Will be comming in next minor release.

**Comment by rsudarson** [comment]
This is a useful feature. Can this be released sooner?

**Comment by FLevent29** [comment]
I am working on it.

**Comment by archfz** [comment]
Two new options coming up in next release that will replace current `printLogs`.

**Comment by archfz** [comment]
Released in 2.1.0.
