### ISSUE TITLE
Feature: print each spec to separate file

### ISSUE THREAD

**Issue by csvan** [archfz/cypress-terminal-report#49]
Given that we have two specs, e,g, 

```
myFirstTest.spec.js 
mySecondTest.spec.js
```

it would be nice if logs from each spec could automatically be printed to e.g:

```
myFirstTest.txt
mySecondTest.txt
```

**Comment by rsudarson** [comment]
This feature will be required if we run tests parallel.  Currently I see some error for parallel test runs.   

```
CypressError: `cy.task('ctrLogFiles')` failed with the following error:
 Cannot read property 'cypress/integration/mock-spec.js' of undefined
```

**Comment by archfz** [comment]
Yeah i was also thinking about this. Hopefully this change can be done without breaking changes. But good point that we need to write tests for the parallel case as well

**Comment by archfz** [comment]
Release in 2.2.0. Please test and give feedback. @rsudarson I could not reproduce those error you pointed out with the parallel cypress pipelines. Can you please retest and provide more detailed error (with stack) and reproduction steps. Also maybe open a separate issue and we will mark it as a bug.
