### ISSUE TITLE
Newly added callback functions are not usable

### ISSUE THREAD

**Issue by vavdagic** [archfz/cypress-terminal-report#64]
If you try to use one of the new callback functions for eg. **collectTestLogs** or **filterLog**, you get the message _"Additional properties not allowed"_. I also didn't see them added to the **PluginOptions** interface.

**Comment by archfz** [comment]
Are you sure you are on version 1.3.0?
It seems to be added and we also have integration tests on it https://github.com/archfz/cypress-terminal-report/blob/fc9e023e903ea4ba7546119dd0741557e4eef9dc/src/installLogsPrinter.schema.json#L50

**Comment by vavdagic** [comment]
@archfz I am using "cypress-terminal-report": "^2.3.0", not 1.3.0 (probably a typo)

**Comment by vavdagic** [comment]
my bad, I was using `installLogsPrinter` instead of `installLogsCollector`

**Comment by archfz** [comment]
hmm. but it should work in both

**Comment by archfz** [comment]
I have tested this in the demo repository and it seems to be working fine on both the plugin and support install options. Closing for now.

**Comment by vavdagic** [comment]
@archfz could you please provide me an example of usage?

**Comment by archfz** [comment]
```diff
diff --git a/cypress/plugins/index.js b/cypress/plugins/index.js
index a4022f1..0d43db3 100644
--- a/cypress/plugins/index.js
+++ b/cypress/plugins/index.js
@@ -19,7 +19,8 @@ const installLogsPrinter = require('cypress-terminal-report/src/installLogsPrint
  */
 module.exports = (on, config) => {
   installLogsPrinter(on, {
-    printLogsToConsole: "always"
+    printLogsToConsole: "always",
+    collectTestLogs: () => console.log('a'),
   });
   // `on` is used to hook into various events Cypress emits
   // `config` is the resolved Cypress config
diff --git a/cypress/support/index.js b/cypress/support/index.js
index fc18168..5b72230 100644
--- a/cypress/support/index.js
+++ b/cypress/support/index.js
@@ -15,6 +15,8 @@
 
 // Import commands.js using ES2015 syntax:
 import './commands'
-require('cypress-terminal-report/src/installLogsCollector')();
+require('cypress-terminal-report/src/installLogsCollector')({
+  collectTestLogs: () => console.log('b'),
+});
 // Alternatively you can use CommonJS syntax:
 // require('./commands')
```

Please note that in the console you will only see A logged. The B should be logged in the browser console.

**Comment by vavdagic** [comment]
@archfz Thanks!
