### ISSUE TITLE
Disable verbose

### ISSUE THREAD

**Issue by MCFreddie777** [archfz/cypress-terminal-report#71]
The `logOutputTarget` function constantly logs `[cypress-terminal-report] Wrote custom logs to ...` into console. 

It would be great if we could turn off the verbose mode (which could be enabled by default) using some option to reduce bloating the cypress terminal output.

Something like:
```
  require('cypress-terminal-report/src/installLogsPrinter')(on, {
        verbose: false,
        ...
    });
```

**Comment by archfz** [comment]
Released in 3.0.0. https://github.com/archfz/cypress-terminal-report#optionsprocesslog
