### ISSUE TITLE
Prevent output file from being deleted.

### ISSUE THREAD

**Issue by joetidee** [archfz/cypress-terminal-report#72]
It would be good to have a flag to prevent the out file from being deleted each time, as I ned to import this file to read the results and if it disappears then my script will fail to import the file.

**Comment by archfz** [comment]
What do you mean by being deleted each time? Also in which format, where we put all in one file or when we put them per spec? If you mean by each time a new cypress run is made then we must delete it so that we don't duplicate the logs.

**Comment by joetidee** [comment]
This is when messages are out all in one file. Could there be an option just to truncate the file?

**Comment by archfz** [comment]
What I dont understand is why you not run the tests then execute the script and then run another set of tests. Can you explain the use case?

**Comment by joetidee** [comment]
This might be what I have to do, as I have just noticed that the docs say that the logs are written after the spec finishes.

I am trying to capture prop-type errors thrown when testing a react-based application using Cypress. For example:

```
let spy;
Cypress.on('window:before:load', win => {
    spy = cy.spy(win.console, 'error');
});

it(pages.HOME_PAGE, () => {
    cy.visit(url);
    cy.get('[data-cypress="react-page"]', { timeout: 60000 });
      
    cy.window().then(() => {
        const matched = spy.args.find(msg => {
            // Here I check against a file containing a list of KNOWN prop type errors. If a match is found, do not fail the test.
        });
        if (matched) {
            expect(spy, 'New Prop Type Errors Found').not.to.be.called;
        }
    });
});
```

In the above snippet, I am using cypress-terminal-report to compare the prop-type errors that occur during the running of a test. If the error(s) are already known, then do not fail the test, else, fail the test.

**Comment by archfz** [comment]
Well this plugins purpose is logging and not controlling when tests fail or not. So yeah you should handle this either with another plugin specific for this purpose or as you posted the code above you can implement it yourself. 

Note that this plugin is also overriding the window.console.[methods] to capture and log those. In case you are also overriding the way you posted the logging for these might not work anymore.

Closing this as not in the scope of the plugin.

**Comment by joetidee** [comment]
I am using this package to generate the error logs against which I can compare the test errors against, so this is not out of scope. I'm just asking for a switch to truncate the file instead of delete it.

**Comment by archfz** [comment]
I still dont understand. After you run 'npx cypress run' arent the log files there?

**Comment by joetidee** [comment]
The log files are there. But when you run it afterwards, the file is recreated, so it momentarily disappears.

**Comment by archfz** [comment]
Ok. Then why cant you run your script between the cypress runs? Are you running your script during the testing? Please explain in detail when you want to run it.

**Comment by archfz** [comment]
Sorry but I dont see a hard requirement for this feature. But if you really want it feel free to open a PR.
