### ISSUE TITLE
Logging does not work with cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by ifilatov** [archfz/cypress-terminal-report#73]
Hi,
can't make the plugin work with cypress-cucumber-preprocessor. Is it unsupported, or just me doing something wrong?

**Comment by archfz** [comment]
Hi. I have never worked with cucumber. It could easily be the case that there is conflict between this and that plugin. 

Since I have not worked with cucumber, I would appreciate if you could investigate the issue. Or at least provide a repo on which we can reproduce the issue.

**Comment by ifilatov** [comment]
Hi, I'm new to TS and not good at tracing the callbacks code, so I was not able to investigate, sorry. That sounds like the issue is in printing part: I've diff'ed the output before and after I've tried to install cypress-terminal-report - and the result is identical (different time for sure).

Here is the fork from cypress-cucumber-example with added integration of cypress-terminal-report: https://github.com/ifilatov/cypress-cucumber-example

**Comment by archfz** [comment]
@ifilatov Sorry for taking so long. Please read the documentation if having issues when using a plugin. The logs are logged only when tests fail by default. I will update the readme to make this clear.

If you want to log always here is the change on your repo:
```diff
diff --git a/cypress/plugins/index.js b/cypress/plugins/index.js
index f14408a..2b7b595 100644
--- a/cypress/plugins/index.js
+++ b/cypress/plugins/index.js
@@ -13,7 +13,9 @@
 
 const cucumber = require('cypress-cucumber-preprocessor').default
 module.exports = (on, config) => {
-  require('cypress-terminal-report/src/installLogsPrinter')(on);
+  require('cypress-terminal-report/src/installLogsPrinter')(on, {
+printLogsToConsole: 'always',
+});
   on('file:preprocessor', cucumber())
 
```
