### ISSUE TITLE
Setting to Mask Sensitive Values in API Request/Response?

### ISSUE THREAD

**Issue by adrian861** [archfz/cypress-terminal-report#74]
First off, love the tool, has been SUPER helpful for some of our node issues.

I was wondering if there's a setting, or way to mask value's for certain keys in API request/response.  For example:

```
      cy:request ✔  POST https://someUrl/v1/graphql
                    Status: 200
                    Response body: {
                      "data": {
                        "authenticate": {
                          "oneTimeToken": "*******",
                          "session_id": "someId",
                          "uuid": "someUuid"
                        }
                      }
```
Currently `oneTimeToken` displays the value during a failure, which we'll want hidden, especially as we move to CI.

**Comment by archfz** [comment]
We should add a processLog just like the filterLog option. Then you can based on log type (xhr) and message do your own regexes to remove these values.

**Comment by archfz** [comment]
Release in 3.0.0. https://github.com/archfz/cypress-terminal-report#optionsprocesslog
