### ISSUE TITLE
Cannot set up individual spec log files

### ISSUE THREAD

**Issue by alastair-todd** [archfz/cypress-terminal-report#77]
Following the readme, I've done this:

```
// set up terminal report plugin
  const outputRoot = path.join(config.projectRoot, 'cypress', 'logs');
  const specRoot = path.join(config.projectRoot, 'cypress', 'integration');
  console.log(`e2e terminal output to: ${outputRoot}`);
  console.log(`e2e spec root: ${specRoot}`);
  const terminalReportOptions = {
    outputRoot,
    specRoot,
    outputTarget: {
      'e2e-output.log': 'txt',
      'e2e-output.json': 'json'
    }
  };
  require('cypress-terminal-report/src/installLogsPrinter')(on, terminalReportOptions);
```

But terminal ouput throws:

> 
> C:\_dev\cloud-ui\e2e> npm run cy:run:layout
> 
> > cloud-e2e@1.0.0 cy:run:layout C:\_dev\cloud-ui\e2e
> > cypress run --browser chrome --headless --spec "cypress/integration/layout/**/*.feature"
> 
> 
> e2e terminal output to: C:\_dev\cloud-ui\e2e\cypress\logs
> e2e spec root: C:\_dev\cloud-ui\e2e\cypress\integration
> The function exported by the plugins file threw an error.
> 
> We invoked the function exported by `C:\_dev\cloud-ui\e2e\cypress\plugins\index.ts`, but it threw an error.
> 
>  Error: [cypress-terminal-report] Invalid plugin install options: 
> => .specRoot: Additional properties not allowed
> 
>     at installLogsPrinter (C:\_dev\cloud-ui\e2e\node_modules\cypress-terminal-report\src\installLogsPrinter.js:63:11)

**Comment by archfz** [comment]
Version of the plugin?

**Comment by archfz** [comment]
`Additional properties not allowed` is a json schema error pointing to the fact that the option provided is not recognized. This most likely means you have and older version that of when the option was introduced. Closing as of inactivity.
