### ISSUE TITLE
How do I see terminal output when running in the cloud?

### ISSUE THREAD

**Issue by andrewryan1906** [archfz/cypress-terminal-report#8]
I've followed the steps to get this working, and then run a Cypress suite of tests in CircleCI. A test failed and I went to see the console terminal output, but couldn't figure out where it was.

The only place I could think it would be was in the Cypress Dashboard; I went to the failed spec and clicked on the "Output" icon to display the output. I got this:

![image](https://user-images.githubusercontent.com/37671394/75002692-45d6ed00-5433-11ea-9858-82cf95afd30a.png)

But none of my console logs are in here.

Where should I be looking?

**Comment by archfz** [comment]
Hello. This is a good questions, I havent used it with the dashboard and I am not sure how the logs get in the dashboard.

Yes the logs should appear after the test title in red. Can you check that if you run your tests locally then you get output on the CLI if it fails. Just so that we narrow the problem.

**Comment by andrewryan1906** [comment]
@archfz I can see them in my CircleCI logs when I view the job step in their console.

Good to go.

**Comment by archfz** [comment]
@andrewryan1906 So basically this means that the logs from this plugin are somehow not appearing in the dashboard? Can you confirm this? In case it's like that we should specify this in the readme, and maybe add a feature request for it, bc it would be important.

**Comment by archfz** [comment]
@andrewryan1906 So what do you say? It would be nice if you could confirm this issue so that we update the readme.

**Comment by andrewryan1906** [comment]
@archfz That's correct - I wasn't able to find them in the dashboard. But the fact that they are in the CircleCI output works for me.

**Comment by archfz** [comment]
Ok then we will add a notice in the readme, and a feature request and if people need it we will attempt to make it work.
