### ISSUE TITLE
Log specs in separate files does not work in conjunction with cypress-cucumber-preprocessor plugin

### ISSUE THREAD

**Issue by adamsjr8576** [archfz/cypress-terminal-report#82]
Hello! This plugin is solving a really awesome problem and it is SO close to working with cypress-cucumber-preprocessor.

I am currently encountering an issue with creating a new log output file per .spec file. When using cypress-cucumber-preprocessor you use .feature files to run a test, so the file structure changes slightly to account for that. When running the tests cypress-terminal-report points to `node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js` when running every test instead of the cypress specs root directory.

And so, each log output file that is created per spec - results in the same name => `createTestFromScenario.json`. When running the tests you can see the file being created for each spec containing the correct info, and then after each subsequent spec runs the file gets overwritten with the new info because it is using the same name. 

So, I can not figure out how to create a unique file name for each spec to avoid overwriting the same file each time?

Here are my current options: 
![Screen Shot 2021-03-10 at 10 58 11 AM](https://user-images.githubusercontent.com/49846853/110674838-86fd8480-818f-11eb-8172-026abf02ad02.png)

Let me know if you need any more information to assist with this issue - thank you!!

Also, side note => when running the format for logging to files (without seperate file syntax) - see screenshot - the same thing is happening - it creates a new file for each feature run, but I am only able to set a static filename so the file gets overwritten everytime. So, it would be working if each feature where run in isolation, but these tests are running in Circle CI and runs a set of features at once using Cypress' "testFiles" config option. I can't figure out how to create a uniquely named file for each run?

**Comment by archfz** [comment]
Fixed in 3.0.1
