### ISSUE TITLE
filterLog not filtering out Severity of 'warning' for Type of 'cy:xhr'

### ISSUE THREAD

**Issue by adamsjr8576** [archfz/cypress-terminal-report#84]
Hello Again! 

I'm encountering an issue when attempting to use filterLog to filter out logs based on severity. This is being used in addition to collectType. I have the Types being filtered, but within that I only want to collect and print logs with a Severity of either 'error' or 'warning'. 

Here is the solution that I thought would work for this:
![Screen Shot 2021-03-10 at 12 45 38 PM](https://user-images.githubusercontent.com/49846853/110688192-8ddfc380-819e-11eb-871d-c842a5aba0e3.png)

this yields the result of: (even though there is a 'cy:xhr' with a severity of 'warning' being generated)
![Screen Shot 2021-03-10 at 12 54 26 PM](https://user-images.githubusercontent.com/49846853/110689302-c764fe80-819f-11eb-9a7e-503941d55103.png)

This solution correctly filters out logs with the severity of 'error' but does not filter out the severity of 'warning' for a 'cy:xhr' type. The tests being run to simulate this are generating a 'cy:xhr' warning every time, and without the filters here is a snapshot of that output:
![Screen Shot 2021-03-10 at 12 49 56 PM](https://user-images.githubusercontent.com/49846853/110688761-2d9d5180-819f-11eb-958c-8d8da51bcb19.png)

It looks like the severity on that 'cy:xhr' is set to 'warning', so I am not sure why it is not being filtered out in the above solution. Because I am interested in getting info on XHR requests that fail - I don't care about the one's that have a severity of 'success' as there is a LOT of them. 

Do you see anything that I am doing incorrectly - or know what might be causing this to happen?

Thank you so much!!

**Comment by archfz** [comment]
Fixed in 3.0.1
