### ISSUE TITLE
Request does not print method and url

### ISSUE THREAD

**Issue by pamdevco** [archfz/cypress-terminal-report#9]
Currently `cy.request` does not print any content of the request. It will be good to print the same details as `cy.route`

I tried to add this to `Cypress.on('log:added', options => {` 
```
      if (options.name === 'request' && options.hookName && options.hookName === 'test') {
        options.message = options.renderProps.message;
      }
```
To get more information like status, response I need to wait for the promise in options to resolve. But I don't know how to do that. 

If I `console.log(options) ` the data is in `consoleProps` But `console.log(options.consoleProps)` does show the data. I guess the promise is not resolved. How do I fix this?

**Comment by archfz** [comment]
@pamdevco Yes, this would be a nice feature to have so I am reopening your issues. Will look into it a bit later.

**Comment by archfz** [comment]
Actually now seeing that the issues is duplicated in #10

**Comment by zhex900** [comment]
@pamdevco and @jhepam are my work logins. I don't want to use them.
