### ISSUE TITLE
Logs printed multiple times

### ISSUE THREAD

**Issue by jfairley** [archfz/cypress-terminal-report#92]
I tried out `cypress-terminal-report` for the first time, and the logs printed 3 times. Do you have any suggestions?

My change diff:

<img width="1264" alt="Screen Shot 2021-04-19 at 10 16 47 AM" src="https://user-images.githubusercontent.com/992483/115269417-87772c80-a0f8-11eb-9602-5ac4b4b5f5b9.png">

My CI log output:

![Apr-19-2021 10-19-32](https://user-images.githubusercontent.com/992483/115269777-df159800-a0f8-11eb-8654-10548dcba1fb.gif)

My `cypress.json`:

```json
{
  "baseUrl": "http://127.0.0.1:3000/",
  "integrationFolder": "cypress/integration",
  "reporter": "cypress-multi-reporters",
  "reporterEnabled": "spec, junit",
  "junitReporterOptions": {
    "mochaFile": "reports/test-output.xml"
  },
  "retries": {
    "runMode": 2,
    "openMode": 0
  },
  "testFiles": "**/*.test.ts",
  "viewportWidth": 1920,
  "viewportHeight": 1080
}
```

My versions:

```
    "cypress": "7.0.0",
    "cypress-multi-reporters": "1.4.0",
    "cypress-plugin-tab": "1.0.5",
    "cypress-wait-until": "1.7.1",
```

**Comment by archfz** [comment]
I see you have 2 retries in run mode. Are you sure its not because of the retries? Sorry but cannot really see the logs properly in the gif. Please avoid posting pictures as they are not indexable by search engines.

**Comment by jfairley** [comment]
@archfz I didn't even think of that! I'm sure that's why it printed multiple times. Great call.

Any ideas how to get it to print once? I've never investigated with the `on` callback. I'm curious whether there's info provided that would indicate where cypress is in its "retry" phases... I would only want to print the terminal report after the last retry has failed, but of course the challenge is figuring out when that is.

**Comment by archfz** [comment]
There is no feature for this. There should be a title printed by mocha, dont know why it doesnt print for you. 

Printing for each failure is important as different retries can fail for different reasons.

**Comment by jfairley** [comment]
Good point @archfz. Our tests _usually_ fail repeatedly for the same reason, but your right, that's not necessarily true. I'll just keep it the way it is and inform the team of why they'll see it 3 times.

Thanks for your feedback!

**Comment by archfz** [comment]
For me it prints something like 'try 1 out of 3' before outputing the logs in case retries are enabled, maybe this is broken in cypress 7.x, will check.

**Comment by archfz** [comment]
Added test and it is confirmed working.
