### ISSUE TITLE
3.1.0 breaks compatibility with pre-6.0 cypress

### ISSUE THREAD

**Issue by FFdhorkin** [archfz/cypress-terminal-report#95]
Due to a compatibility issue, we're stuck using Cypress 5.6.0 for the time being.
According to the release notes for 3.x.x of cypress-testrail-reporter, the `Minimum required cypress version increased to 4.10.0.`

However, Cypress didn't introduce the `intercept` command until Cypress 6.0

This means that when you try to use cypress-terminal-report on an older version of cypress, you get an exception and you cannot run tests:
![image](https://user-images.githubusercontent.com/59899746/117044742-a44c5c00-acc3-11eb-9b19-b2e5fdd86b57.png)

That said, cypress-terminal-report 3.0.2 is still compatible with Cypress 5.6.0.

**Comment by FFdhorkin** [comment]
I spoke too soon... 3.0.2 has a different error. This error goes away when I disable the terminal report plugin (or if I upgrade Cypress, but that causes GUI issues on my system):
![image](https://user-images.githubusercontent.com/59899746/117048738-2b033800-acc8-11eb-9374-f33f3f2c73b8.png)

**Comment by archfz** [comment]
Good catch. Thank you for the report on it. Fix released in 3.1.1. Please tests and see if all is ok.

**Comment by FFdhorkin** [comment]
Seems to work! That was fast :) thank you!
